/* Drop Tables */

BEGIN TRANSACTION;

DROP TABLE IF EXISTS DEFINICION;
DROP TABLE IF EXISTS CURSO;
DROP TABLE IF EXISTS HORARIO;
DROP TABLE IF EXISTS PROFESOR;

/* Create Tables */

--BEGIN TRANSACTION;

CREATE TABLE DEFINICION
(
        -- Ej. 40
	ID_CARRERA INT NOT NULL,
        -- Ej. Ingenieria de Sistemas y Computacion
	NOMBRE_CARRERA TEXT NOT NULL,
        -- Ej. 2020-1
	PERIODO TEXT NOT NULL,
	    -- Ej. 1008
	CODIGO_PERIODO INT NOT NULL,

	PRIMARY KEY (ID_CARRERA, CODIGO_PERIODO)
);

CREATE TABLE CURSO
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
    	-- Codigo de la Asignatura. Ej. 300CIP001
	CODIGO TEXT NOT NULL,
        -- Ej. A
	GRUPO TEXT NOT NULL,
        -- Ej. INTRODUCCION A LA PROGRAMACION
	NOMBRE CHAR(50) NOT NULL,
        -- Ej. 40
	ID_CARRERA INT NOT NULL,
        -- Ej. 0012941
	ID_PROFESOR INT,
        -- Ej. 1008
    CODIGO_PERIODO INT NOT NULL,
        -- Semestre en que se dicta el curso en la carrera Ej. 1, 2, 10 
    SEMESTRE INT NOT NULL,

	FOREIGN KEY (ID_CARRERA, CODIGO_PERIODO)
	REFERENCES DEFINICION (ID_CARRERA, CODIGO_PERIODO),
	FOREIGN KEY (ID_PROFESOR)
	REFERENCES PROFESOR (ID),
	UNIQUE (CODIGO, GRUPO, CODIGO_PERIODO)
);

CREATE TABLE HORARIO
(
		-- Id de la Asignatura.
	ID_CURSO INTEGER NOT NULL,
		-- Ej. Lunes
	DIA TEXT NOT NULL,
		-- Ej. 7.0 (siete de la mañana), 13.5 (Una y media de la tarde)
	HORAINICIO REAL NOT NULL,
		-- Ej. 9.0 (nueve de la mañana), 15.5 (tres y media de la tarde)
	HORAFIN REAL NOT NULL,

	FOREIGN KEY (ID_CURSO)
	REFERENCES CURSO (ID)
);

CREATE TABLE PROFESOR
(
        -- Ej. 0012941
	ID INT PRIMARY KEY NOT NULL,
        -- EJ. Sarria Montemiranda, Gerardo Mauricio
	NOMBRE TEXT NOT NULL,
        -- Ej. HC, MT, TC
	VINCULACION TEXT
);

COMMIT;